### ISSUE TITLE
Typo in v1.3.1 tar.gz

### ISSUE THREAD

**Issue by BenjaminRodenberg** [precice/openfoam-adapter#337] opened 2024-08-16 08:56 UTC
If I download and extract `openfoam-adapter-v1.3.1-OpenFOAMv1812-v2406-newer.tar.gz` from https://github.com/precice/openfoam-adapter/releases/tag/v1.3.1 I get the following:

```
~/Downloads$ tree -L 2 openfoam-adapter-v1.3.1-OpenFOAMv1812-v2406-newer
openfoam-adapter-v1.3.1-OpenFOAMv1812-v2406-newer
└── openefoam-adapter-v1.3.1-master
    ├── Adapter.C
    ├── Adapter.H
    ...
    └── wmake.log
```

`openefoam-adapter` looks to me like a typo. But I could not easily find the place where it originates from

**Comment by MakisH** [comment] 2024-08-20 11:46
Thanks for spotting this! The root cause has been fixed in https://github.com/precice/openfoam-adapter/commit/70afffe36e039be7ad9de205ec772b4acbb782d8

I will not update the release archives, as this would change their checksums, but the next versions will be fine.

**Closed by MakisH** 2024-08-20 11:46 UTC
Labels: building
