### ISSUE TITLE
Extend the 2D mode to only set one layer of vertices

### ISSUE THREAD

**Issue by MakisH** [precice/openfoam-adapter#146] opened 2020-11-17 21:10 UTC
In https://github.com/precice/openfoam-adapter/pull/96, we added support for 2D solver interfaces. In that case, the adapter can skip the third dimension in vertices and data, such as here:

https://github.com/precice/openfoam-adapter/blob/8ae5f061ab26ae059b8cdcf304089306f9ce7227/Interface.C#L142-L148

However, we still pass all the patch nodes to preCICE:

https://github.com/precice/openfoam-adapter/blob/8ae5f061ab26ae059b8cdcf304089306f9ce7227/Interface.C#L105

This works nicely, but it can still lead to the RBF mapping issue described in https://github.com/precice/tutorials/issues/112.

What we need is to distinguish the two layers of nodes and only select the one (usually "front" or "back"). Alternatives I can think of:
- maybe we can do this directly with an OpenFOAM method (I don't know if such a method exists, but this would be ideal)
- we somehow select points that belong to two patches: the interface and the front or back "empty" boundary.
- we manually find the two repeating z (or x, or y) values and add only the points we want to a list. I can imagine that this solution would be quite difficult to maintain.

In any case, we should see how each alternative affects the rest of the code. If we need to manually find the correct points every time we write/read data, that would be risky.

This is a requirement for https://github.com/precice/tutorials/issues/117.

**Comment by DavidSCN** [comment] 2020-12-03 11:45
I still don't know why the RBF mappings trigger issues since we enforce continuity across duplicated nodes. However, here some considerations regarding the implementation of this extension:

Skipping the duplicated node during the initialization is only half the rent: we still need to set the boundary condition according to both layers in order to work with the current  setup. Therefore, the first two options are not suitable in my opinion, because we have no information about the dropped vertices. The best solution is probably to utilize a feature we have implemented for the nearest-projection mappings, which interpolates between face nodes and face centers using OF internals: one needs to select `faceCenters` in the precice dictionary and the mapping between face centers and face nodes happens in the adapter itself. Since there is only one 'layer' of face centers in the OF mesh the problem is resolved and the main driver for this method is OF internal functionality. I have not yet tested the concept but I assume that it would work.
On the one hand, a desirable side effect would be the elimination of the annoying second OF mesh during the configuration of preCICE. On the other hand, the additional interpolation step is probably undesired in 3D (for performance reasons) and the user needs to change the configuration when switching from 2D to 3D (i.e. inconsistencies between 2D and 3D in OF). 

A more general consideration: since the final mesh movement is solved using the `cellDisplacement` field in OF, which is based on cell centers rather then points, can't we set the boundary condition directly on the face centers in order to avoid interpolations or tedious configurations? The 'point infrastructure' is only used for displacement reading. I just set up a small test case where the cell centers are used rather than the points and it works, though there are still small differences (cf figure). Before starting now with anything more in detail I would like to collect some opinions. What do others think?
![](https://user-images.githubusercontent.com/33414590/101013573-cc912c80-3564-11eb-93b8-d86642a13b57.png)

**Comment by uekerman** [comment] 2020-12-04 08:42
> I still don't know why the RBF mappings trigger issues since we enforce continuity across duplicated nodes.

How we use it right now for the FSI3 is indeed safe, but there are other situation where we might get problems. For instance if you want to write velocity values. Then you get two duplicated rows in the RBF system, which makes the system singular. 

> Skipping the duplicated node during the initialization is only half the rent: we still need to set the boundary condition according to both layers in order to work with the current setup.

Exactly.

> On the one hand, a desirable side effect would be the elimination of the annoying second OF mesh during the configuration of preCICE. On the other hand, the additional interpolation step is probably undesired in 3D (for performance reasons) and the user needs to change the configuration when switching from 2D to 3D (i.e. inconsistencies between 2D and 3D in OF).

In my opinion that would be OK. Changing from 2D to 3D is not sth that you do regularly when modifying a testcase. Also in the preCICE config you have to change already the dimensions from 2 to 3. The two meshes, you currently also only need for FSI, for other coupling physics you might not need them ([e.g. fluid-fluid](https://github.com/precice/openfoam-adapter/blob/FF/tutorials
/FF/pipe-pipe/pimpleFoam-pimpleFoam/precice-config.xml)). I guess what I want to say: it is OK to modify the configuration files if the changes make sense for a user.

> A more general consideration: since the final mesh movement is solved using the cellDisplacement field in OF, which is based on cell centers rather then points, can't we set the boundary condition directly on the face centers in order to avoid interpolations or tedious configurations? The 'point infrastructure' is only used for displacement reading. I just set up a small test case where the cell centers are used rather than the points and it works, though there are still small differences (cf figure). Before starting now with anything more in detail I would like to collect some opinions. What do others think?

For FSI and 2D that sounds like a great solution to me.

**Comment by MakisH** [comment] 2020-12-07 07:51
> A more general consideration: since the final mesh movement is solved using the `cellDisplacement` field in OF, which is based on cell centers rather then points, can't we set the boundary condition directly on the face centers in order to avoid interpolations or tedious configurations? The 'point infrastructure' is only used for displacement reading. I just set up a small test case where the cell centers are used rather than the points and it works, though there are still small differences (cf figure). Before starting now with anything more in detail I would like to collect some opinions. What do others think?

This is something I had not tried before, but it makes a lot of sense. Let's [document this](https://github.com/precice/openfoam-adapter/wiki/Configuration#fsi) (I will port it to the new website later) and update our tutorials.

Would it be useful to actually keep the "reading on mesh nodes" functionality then? Do we have a reason to prefer it in 3D simulations? If not, removing it would also simplify the code.

**Comment by DavidSCN** [comment] 2020-12-07 12:50
> Would it be useful to actually keep the "reading on mesh nodes" functionality then? Do we have a reason to prefer it in 3D simulations? If not, removing it would also simplify the code.

I know, we could remove the complete node infrastructure and make the life of our user much easier. However, I will implement the interpolation option in a first step. Otherwise I need to figure out the reason for differences here and this might take a while.

**Comment by MakisH** [comment] 2020-12-07 13:22
Whatever you think is best! :smiley:

**Comment by JSeuffert** [comment] 2020-12-08 09:09
In my experience, the OpenFOAM interpolation from face centers to points does not work perfect at sharp edges, where you interpolate from two sides to a point on the edge. Maybe this is what causes the small differences here?

I think that is also why they use a least squares interpolation or an edgeCorrectedVolPointInterpolation in the solid mechanics solvers in foam-extend. For example here: 
https://sourceforge.net/p/foam-extend/foam-extend-4.1/ci/master/tree/applications/solvers/solidMechanics/elasticNonLinULSolidFoam/
I don't have a lot of knowledge of the interpolation algorithms though...

In general I think its a great idea to get rid of the node based definitions!

**Comment by DavidSCN** [comment] 2020-12-08 10:13
I see your point and agree that there is a loss of accuracy on the OpenFOAM side in the corners and it could be a potential reason. On the other hand, I need to modify the boundary conditions of the `pointDisplacement` field slightly so that they follow the `cellDisplacement` motion, which could also be a reason. 
In order to get a first impression of the differences originating from different mappings/interpolation (in OpenFOAM and preCICE) one could simply drive the mapping resolution in the OpenFOAM mesh to the limit since any related differences should vanish in this case. 
Also, the slightly different implementation in #147 should suffer from the same interpolation issue and it is probably a good reference case.

**Comment by DavidSCN** [comment] 2020-12-18 13:35
Closed via #147

**Closed by DavidSCN** 2020-12-18 13:35 UTC
Labels: enhancement
