### ISSUE TITLE
empty pkg-config Cflags  despite correct libprecice.pc file

### ISSUE THREAD

**Issue by mojtabaAmiraslanpour** [precice/openfoam-adapter#137] opened 2020-08-13 06:53 UTC
While compiling the OpenFOAM 7.0 adapter on PreCICE 2.1 (installed by using binary DEB packages on Ubuntu 18.04.1), header files are not found. I found that `pkg-config --cflags libprecice` returns empty.

I used the procedure mentioned in [here](https://unix.stackexchange.com/questions/362289/why-is-pkg-config-cflags-openssl-returning-nothing-on-rhel-6-8) to change the line which returns the path to the header files in the Allwmake file:
```
export ADAPTER_PKG_CONFIG_CFLAGS="`PKG_CONFIG_ALLOW_SYSTEM_CFLAGS=1 pkg-config --cflags libprecice`"
```
And this fixed the issue.

**Comment by MakisH** [comment] 2020-08-13 10:57
Thank you for reporting this, @mojtabaAmiraslanpour!

It is true that pkgconfig ignores the paths known to the system, but this shouldn't be a problem, exactly because the paths are already known.

I am currently a bit confused on why you got this problem and why this change fixed it. I am not sure if this is related, but did you also start a new terminal in the meantime?

I will try to reproduce your issue, please also let me know in case you have more details that could help.

**Comment by mojtabaAmiraslanpour** [comment] 2020-08-13 11:16
my precice header files are located inside `/usr/include/precice` folder. Is that the normal installation?
While executing the Allwmake file before the edit, I got `No such file or directory` errors for the header files.

**Comment by MakisH** [comment] 2020-08-13 11:20
> my precice header files are located inside `/usr/include/precice` folder. Is that the normal installation?

Yes, this is the normal installation, and adapters should use preCICE as e.g.:
https://github.com/precice/openfoam-adapter/blob/c49b862aab4845ae79b8b7257a20e15ba5a0019c/Adapter.H#L22

This means that looking into `/usr/include` (a standard path) should be enough.

I will look into this closer.

**Comment by MakisH** [comment] 2020-09-26 13:53
@mojtabaAmiraslanpour did you have any news or any other details regarding this that would help me to reproduce it?

**Comment by MakisH** [comment] 2022-02-08 22:33
I believe this has probably been fixed with https://github.com/precice/openfoam-adapter/pull/157

**Closed by MakisH** 2022-02-08 22:33 UTC
